<a href="https://colab.research.google.com/github/Aashutosh-Basnet/Aashutosh-Basnet/blob/main/logistic_regression/multi_class/MultiClass_LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [5]:
data = load_iris()

df = pd.DataFrame(data = data.data, columns = data.feature_names)

df['target'] = data.target

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [6]:
print(df['target'])

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64


In [7]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [8]:
X = df.drop(columns = ['target'])
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)


In [11]:
from sklearn.metrics import accuracy_score

logreg = LogisticRegression(multi_class = 'multinomial', solver = 'lbfgs', max_iter = 200)

logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print(f'Accuracy: {accuracy * 100:.2f}%')

# Optionally, print the predicted probabilities for each class
y_probs = logreg.predict_proba(X_test)
print("\nPredicted probabilities for the first 5 samples:\n", y_probs[:5])

Accuracy: 100.00%

Predicted probabilities for the first 5 samples:
 [[3.80449169e-03 8.27740592e-01 1.68454917e-01]
 [9.46980854e-01 5.30189471e-02 1.98740436e-07]
 [8.86448725e-09 1.54857657e-03 9.98451415e-01]
 [6.48686229e-03 7.92228036e-01 2.01285102e-01]
 [1.45812219e-03 7.74128948e-01 2.24412929e-01]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
